backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "content"
        label: "Contenu de la Page d'Accueil"
        file: "content.json"
        fields:
          - { label: "Métadonnées (SEO)", name: "meta", widget: "object", fields: [
              { label: "Titre de la page", name: "title", widget: "string" },
              { label: "Description de la page", name: "description", widget: "text" }
            ]}
          - { label: "En-tête (Header)", name: "header", widget: "object", fields: [
              { label: "Titre du logo", name: "logo_title", widget: "string" },
              { label: "Sous-titre du logo", name: "logo_subtitle", widget: "string" },
              { label: "Liens de navigation", name: "nav_links", widget: "list", fields: [
                  { label: "Texte", name: "text", widget: "string" },
                  { label: "Lien (ex: #about)", name: "href", widget: "string" }
                ]},
              { label: "Bouton d'action", name: "cta_button", widget: "object", fields: [
                  { label: "Texte", name: "text", widget: "string" },
                  { label: "Lien", name: "href", widget: "string" }
                ]}
            ]}
          - { label: "Section Héros", name: "hero", widget: "object", fields: [
              { label: "Image de fond", name: "background_image", widget: "image" },
              { label: "Titre (partie 1)", name: "title_part1", widget: "string" },
              { label: "Titre (partie 2, en surbrillance)", name: "title_part2", widget: "string" },
              { label: "Sous-titre", name: "subtitle", widget: "text" },
              { label: "Bouton d'action principal", name: "primary_cta", widget: "object", fields: [
                  { label: "Texte", name: "text", widget: "string" },
                  { label: "Lien", name: "href", widget: "string" }
                ]},
              { label: "Bouton d'action secondaire", name: "secondary_cta", widget: "object", fields: [
                  { label: "Texte", name: "text", widget: "string" },
                  { label: "Lien", name: "href", widget: "string" }
                ]}
            ]}
          - { label: "Section À Propos", name: "about", widget: "object", fields: [
              { label: "Titre (partie 1)", name: "title_part1", widget: "string" },
              { label: "Titre (partie 2, en surbrillance)", name: "title_part2", widget: "string" },
              { label: "Paragraphes", name: "paragraphs", widget: "list", field: { label: "Paragraphe", name: "p", widget: "string" } },
              { label: "Bouton Instagram", name: "instagram_button", widget: "object", fields: [
                  { label: "Texte", name: "text", widget: "string" },
                  { label: "Lien", name: "href", widget: "string" }
                ]},
              { label: "Image", name: "image", widget: "object", fields: [
                  { label: "Fichier image", name: "src", widget: "image" },
                  { label: "Texte alternatif", name: "alt", widget: "string" }
                ]}
            ]}
          - { label: "Section Cours & Formules", name: "services", widget: "object", fields: [
              { label: "Titre (partie 1)", name: "title_part1", widget: "string" },
              { label: "Titre (partie 2, en surbrillance)", name: "title_part2", widget: "string" },
              { label: "Sous-titre", name: "subtitle", widget: "string" },
              { label: "Formules", name: "plans", widget: "list", fields: [
                  { label: "Populaire ?", name: "popular", widget: "boolean", default: false },
                  { label: "Code SVG de l'icône", name: "icon_svg", widget: "text" },
                  { label: "Titre", name: "title", widget: "string" },
                  { label: "Sous-titre", name: "subtitle", widget: "string" },
                  { label: "Description", name: "description", widget: "text" },
                  { label: "Prix", name: "price", widget: "string" },
                  { label: "Bouton", name: "button", widget: "object", fields: [
                      { label: "Texte", name: "text", widget: "string" },
                      { label: "Lien", name: "href", widget: "string" }
                    ]}
                ]},
              { label: "Lien en bas de section", name: "bottom_link", widget: "object", fields: [
                  { label: "Texte", name: "text", widget: "string" },
                  { label: "Lien", name: "href", widget: "string" }
                ]}
            ]}
          - { label: "Section Galerie", name: "gallery", widget: "object", fields: [
              { label: "Titre (partie 1)", name: "title_part1", widget: "string" },
              { label: "Titre (partie 2, en surbrillance)", name: "title_part2", widget: "string" },
              { label: "Sous-titre", name: "subtitle", widget: "string" },
              { label: "Images", name: "images", widget: "list", fields: [
                  { label: "Fichier image", name: "src", widget: "image" },
                  { label: "Texte alternatif", name: "alt", widget: "string" },
                  { label: "Classes CSS (optionnel, ex: col-span-2 md:row-span-2)", name: "css_class", widget: "string", required: false }
                ]},
              { label: "Texte en bas de section", name: "footer_text", widget: "string" }
            ]}
          - { label: "Section Témoignages", name: "testimonials", widget: "object", fields: [
              { label: "Titre (partie 1)", name: "title_part1", widget: "string" },
              { label: "Titre (partie 2, en surbrillance)", name: "title_part2", widget: "string" },
              { label: "Sous-titre", name: "subtitle", widget: "string" },
              { label: "Témoignages", name: "items", widget: "list", fields: [
                  { label: "Citation", name: "quote", widget: "text" },
                  { label: "Initiales", name: "initials", widget: "string" },
                  { label: "Nom", name: "name", widget: "string" },
                  { label: "Rôle/Profession", name: "role", widget: "string" }
                ]},
              { label: "Texte en bas de section", name: "footer_text", widget: "string" }
            ]}
          - { label: "Section FAQ", name: "faq", widget: "object", fields: [
              { label: "Titre (partie 1)", name: "title_part1", widget: "string" },
              { label: "Titre (partie 2, en surbrillance)", name: "title_part2", widget: "string" },
              { label: "Sous-titre", name: "subtitle", widget: "string" },
              { label: "Questions/Réponses", name: "items", widget: "list", fields: [
                  { label: "Question", name: "question", widget: "string" },
                  { label: "Réponse", name: "answer", widget: "text" }
                ]},
              { label: "Texte en bas de section", name: "footer_text", widget: "string" }
            ]}
          - { label: "Section Réservation", name: "booking", widget: "object", fields: [
              { label: "Titre (partie 1)", name: "title_part1", widget: "string" },
              { label: "Titre (partie 2, en surbrillance)", name: "title_part2", widget: "string" },
              { label: "Sous-titre", name: "subtitle", widget: "string" },
              { label: "Cartes d'information", name: "info_cards", widget: "list", fields: [
                  { label: "Code SVG de l'icône", name: "icon_svg", widget: "text" },
                  { label: "Titre", name: "title", widget: "string" },
                  { label: "Texte", name: "text", widget: "string" }
                ]},
              { label: "Planning", name: "planning", widget: "object", fields: [
                  { label: "Titre du planning", name: "title", widget: "string" },
                  { label: "Sous-titre du planning", name: "subtitle", widget: "string" },
                  { label: "Jours", name: "days", widget: "list", fields: [
                      { label: "Nom du jour", name: "name", widget: "string" },
                      { label: "Cours", name: "classes", widget: "list", fields: [
                          { label: "Heure", name: "time", widget: "string" },
                          { label: "Nom du cours", name: "name", widget: "string" },
                          { label: "Disponibilité", name: "availability", widget: "string" },
                          { label: "Statut", name: "status", widget: "select", options: ["available", "full"] },
                          { label: "Texte du bouton", name: "button_text", widget: "string" }
                        ]}
                    ]}
                ]},
              { label: "Bouton en bas de section", name: "bottom_button", widget: "object", fields: [
                  { label: "Texte", name: "text", widget: "string" },
                  { label: "Lien", name: "href", widget: "string" }
                ]}
            ]}
          - { label: "Section Contact", name: "contact", widget: "object", fields: [
              { label: "Titre (partie 1)", name: "title_part1", widget: "string" },
              { label: "Titre (partie 2, en surbrillance)", name: "title_part2", widget: "string" },
              { label: "Sous-titre", name: "subtitle", widget: "string" },
              { label: "Cartes d'information", name: "info_cards", widget: "list", fields: [
                  { label: "Code SVG de l'icône", name: "icon_svg", widget: "text" },
                  { label: "Titre", name: "title", widget: "string" },
                  { label: "Lignes de texte", name: "lines", widget: "list", field: { label: "Ligne", name: "line", widget: "string" } },
                  { label: "Note de bas de page", name: "footnote", widget: "string" }
                ]},
              { label: "Bloc d'appel à l'action", name: "cta", widget: "object", fields: [
                  { label: "Titre", name: "title", widget: "string" },
                  { label: "Texte", name: "text", widget: "text" },
                  { label: "Bouton principal", name: "primary_button", widget: "object", fields: [
                      { label: "Texte", name: "text", widget: "string" },
                      { label: "Lien", name: "href", widget: "string" }
                    ]},
                  { label: "Bouton secondaire", name: "secondary_button", widget: "object", fields: [
                      { label: "Texte", name: "text", widget: "string" },
                      { label: "Lien", name: "href", widget: "string" }
                    ]}
                ]},
              { label: "Image de la carte", name: "map", widget: "object", fields: [
                  { label: "Fichier image", name: "src", widget: "image" },
                  { label: "Texte alternatif", name: "alt", widget: "string" }
                ]}
            ]}
          - { label: "Pied de page (Footer)", name: "footer", widget: "object", fields: [
              { label: "Titre du logo", name: "logo_title", widget: "string" },
              { label: "Sous-titre du logo", name: "logo_subtitle", widget: "string" },
              { label: "Description", name: "description", widget: "text" },
              { label: "Liens réseaux sociaux", name: "social_links", widget: "list", fields: [
                  { label: "Lien", name: "href", widget: "string" },
                  { label: "Code SVG de l'icône", name: "icon_svg", widget: "text" }
                ]},
              { label: "Titre de la navigation", name: "nav_title", widget: "string" },
              { label: "Liens de navigation", name: "nav_links", widget: "list", fields: [
                  { label: "Texte", name: "text", widget: "string" },
                  { label: "Lien", name: "href", widget: "string" }
                ]},
              { label: "Titre du contact", name: "contact_title", widget: "string" },
              { label: "Infos de contact (HTML)", name: "contact_info_html", widget: "markdown" },
              { label: "Copyright", name: "copyright", widget: "string" },
              { label: "Liens légaux", name: "legal_links", widget: "list", fields: [
                  { label: "Texte", name: "text", widget: "string" },
                  { label: "Lien", name: "href", widget: "string" }
                ]}
            ]}
